In [1]:
import pandas as pd

***skiprows pula linha; delimiter em vez de , utilizamos o ; e o encoding para padrão latino***

In [2]:
df = pd.read_csv('ceaps_dataset.csv', skiprows=1, delimiter=';', encoding='latin1')

In [3]:
df.head()

,ANO,MES,SENADOR,TIPO_DESPESA,CNPJ_CPF,FORNECEDOR,DOCUMENTO,DATA,DETALHAMENTO,VALOR_REEMBOLSADO
0,2016,1,ACIR GURGACZ,"Aluguel de imóveis para escritório político, c...",05.914.650/0001-66,ELETROBRÁS DISTRIBUIÇÃO RONDÔNIA,000011328,13/01/2016,Despesa com pagamento de energia elétrica para...,"73,6"
1,2016,1,ACIR GURGACZ,"Aluguel de imóveis para escritório político, c...",05.914.650/0001-66,ELETROBRÁS DISTRIBUIÇÃO RONDÔNIA,000011327,18/01/2016,Pagamento de energia elétrica para o escritóri...,"206,84"
2,2016,1,ACIR GURGACZ,"Aluguel de imóveis para escritório político, c...",004.948.028-63,GILBERTO PISELO DO NASCIMENTO,001/16,04/01/2016,"Despesa com pagamento de aluguel, utilizado pa...",6000
3,2016,1,ACIR GURGACZ,"Aluguel de imóveis para escritório político, c...",05.423.963/0001-11,OI MÓVEL S.A.,661639001,16/01/2016,despesa com pagamento de telefonia para o escr...,"407,48"
4,2016,1,ACIR GURGACZ,Aquisição de material de consumo para uso no e...,62.652.961/0001-38,AGÊNCIA ESTADO S.A.,00608918,06/01/2016,Aquisição de publicação virtual de conteúdo jo...,550

In [4]:
df.tail()

,ANO,MES,SENADOR,TIPO_DESPESA,CNPJ_CPF,FORNECEDOR,DOCUMENTO,DATA,DETALHAMENTO,VALOR_REEMBOLSADO
26686,2016,12,ZEZÉ PERRELLA,"Locomoção, hospedagem, alimentação, combustíve...",01.245.727/0001-00,Trevo Posto de Serviços Ltda,083555,23/12/2016,NaN,"183,4"
26687,2016,12,ZEZÉ PERRELLA,"Locomoção, hospedagem, alimentação, combustíve...",01.245.727/0001-00,Trevo Posto de Serviços Ltda,084787,26/12/2016,NaN,50
26688,2016,12,ZEZÉ PERRELLA,"Passagens aéreas, aquáticas e terrestres nacio...",09.296.295/0001-60,Azul,QGIJ8X,07/12/2016,"Companhia Aérea: AZUL, Localizador: QGIJ8X. Pa...","1055,41"
26689,2016,12,ZEZÉ PERRELLA,"Passagens aéreas, aquáticas e terrestres nacio...",21.443.582/0001-50,Pronto Produção de Eventos e Turismo Ltda,S6ZB6L,12/12/2016,"Companhia Aérea: AZUL, Localizador: S6ZB6L. Pa...","390,18"
26690,2016,12,ZEZÉ PERRELLA,"Passagens aéreas, aquáticas e terrestres nacio...",21.443.582/0001-50,Pronto Produção de Eventos e Turismo Ltda,ZDS6KY,12/12/2016,"Companhia Aérea: GOL, Localizador: ZDS6KY. Pas...","654,28"

In [5]:
df.dtypes

ANO                   int64
MES                   int64
SENADOR              object
TIPO_DESPESA         object
CNPJ_CPF             object
FORNECEDOR           object
DOCUMENTO            object
DATA                 object
DETALHAMENTO         object
VALOR_REEMBOLSADO    object
dtype: object

In [6]:
df['DATA']

0        13/01/2016
1        18/01/2016
2        04/01/2016
3        16/01/2016
4        06/01/2016
5        13/01/2016
6        19/01/2016
7        19/01/2016
8        21/01/2016
9        21/01/2016
10       25/01/2016
11       08/01/2016
12       14/01/2016
13       18/01/2016
14       15/02/2016
15       18/02/2016
16       03/02/2016
17       06/02/2016
18       02/02/2016
19       15/02/2016
20       11/02/2016
21       26/02/2016
22       29/02/2016
23       29/02/2016
24       29/02/2016
25       01/02/2016
26       29/02/2016
27       22/02/2016
28       25/02/2016
29       08/03/2016
            ...
26661    23/12/2016
26662    10/12/2016
26663    24/12/2016
26664    05/12/2016
26665    09/12/2016
26666    10/12/2016
26667    12/12/2016
26668    14/12/2016
26669    29/12/2016
26670    28/12/2016
26671    06/12/2016
26672    09/12/2016
26673    13/12/2016
26674    29/12/2016
26675    12/12/2016
26676    09/12/2016
26677    13/12/2016
26678    20/12/2016
26679    15/12/2016
26680    05/12/2016
26681    07/12/2016
26682    25/12/2016
26683    14/12/2016
26684    14/12/2016
26685    12/12/2016
26686    23/12/2016
26687    26/12/2016
26688    07/12/2016
26689    12/12/2016
26690    12/12/2016
Name: DATA, Length: 26691, dtype: object

In [9]:
df['DATA'] = df['DATA'].str.replace('/','-')

In [35]:
df['DATE'] = pd.to_datetime(df['DATA'])#, errors='coerce').isnull().sum()

In [28]:
df[df["DATA"] == '31-10-200']

Empty DataFrame
Columns: [ANO, MES, SENADOR, TIPO_DESPESA, CNPJ_CPF, FORNECEDOR, DOCUMENTO, DATA, DETALHAMENTO, VALOR_REEMBOLSADO]
Index: []

In [32]:
df['DATA'] = df['DATA'].str.replace('206', '2016')

In [36]:
df.dtypes

ANO                           int64
MES                           int64
SENADOR                      object
TIPO_DESPESA                 object
CNPJ_CPF                     object
FORNECEDOR                   object
DOCUMENTO                    object
DATA                         object
DETALHAMENTO                 object
VALOR_REEMBOLSADO            object
DATE                 datetime64[ns]
dtype: object

In [39]:
df['DIA'] = df['DATE'].dt.day

In [40]:
df.head()

,ANO,MES,SENADOR,TIPO_DESPESA,CNPJ_CPF,FORNECEDOR,DOCUMENTO,DATA,DETALHAMENTO,VALOR_REEMBOLSADO,DATE,DIA
0,2016,1,ACIR GURGACZ,"Aluguel de imóveis para escritório político, c...",05.914.650/0001-66,ELETROBRÁS DISTRIBUIÇÃO RONDÔNIA,000011328,13-01-2016,Despesa com pagamento de energia elétrica para...,"73,6",2016-01-13,13
1,2016,1,ACIR GURGACZ,"Aluguel de imóveis para escritório político, c...",05.914.650/0001-66,ELETROBRÁS DISTRIBUIÇÃO RONDÔNIA,000011327,18-01-2016,Pagamento de energia elétrica para o escritóri...,"206,84",2016-01-18,18
2,2016,1,ACIR GURGACZ,"Aluguel de imóveis para escritório político, c...",004.948.028-63,GILBERTO PISELO DO NASCIMENTO,001/16,04-01-2016,"Despesa com pagamento de aluguel, utilizado pa...",6000,2016-04-01,1
3,2016,1,ACIR GURGACZ,"Aluguel de imóveis para escritório político, c...",05.423.963/0001-11,OI MÓVEL S.A.,661639001,16-01-2016,despesa com pagamento de telefonia para o escr...,"407,48",2016-01-16,16
4,2016,1,ACIR GURGACZ,Aquisição de material de consumo para uso no e...,62.652.961/0001-38,AGÊNCIA ESTADO S.A.,00608918,06-01-2016,Aquisição de publicação virtual de conteúdo jo...,550,2016-06-01,1

In [41]:
df['VALOR_REEMBOLSADO'] = df['VALOR_REEMBOLSADO'].str.replace(',','.')

In [42]:
df.head()

,ANO,MES,SENADOR,TIPO_DESPESA,CNPJ_CPF,FORNECEDOR,DOCUMENTO,DATA,DETALHAMENTO,VALOR_REEMBOLSADO,DATE,DIA
0,2016,1,ACIR GURGACZ,"Aluguel de imóveis para escritório político, c...",05.914.650/0001-66,ELETROBRÁS DISTRIBUIÇÃO RONDÔNIA,000011328,13-01-2016,Despesa com pagamento de energia elétrica para...,73.6,2016-01-13,13
1,2016,1,ACIR GURGACZ,"Aluguel de imóveis para escritório político, c...",05.914.650/0001-66,ELETROBRÁS DISTRIBUIÇÃO RONDÔNIA,000011327,18-01-2016,Pagamento de energia elétrica para o escritóri...,206.84,2016-01-18,18
2,2016,1,ACIR GURGACZ,"Aluguel de imóveis para escritório político, c...",004.948.028-63,GILBERTO PISELO DO NASCIMENTO,001/16,04-01-2016,"Despesa com pagamento de aluguel, utilizado pa...",6000,2016-04-01,1
3,2016,1,ACIR GURGACZ,"Aluguel de imóveis para escritório político, c...",05.423.963/0001-11,OI MÓVEL S.A.,661639001,16-01-2016,despesa com pagamento de telefonia para o escr...,407.48,2016-01-16,16
4,2016,1,ACIR GURGACZ,Aquisição de material de consumo para uso no e...,62.652.961/0001-38,AGÊNCIA ESTADO S.A.,00608918,06-01-2016,Aquisição de publicação virtual de conteúdo jo...,550,2016-06-01,1

In [43]:
df.dtypes

ANO                           int64
MES                           int64
SENADOR                      object
TIPO_DESPESA                 object
CNPJ_CPF                     object
FORNECEDOR                   object
DOCUMENTO                    object
DATA                         object
DETALHAMENTO                 object
VALOR_REEMBOLSADO            object
DATE                 datetime64[ns]
DIA                           int64
dtype: object

In [45]:
df['VALOR_REEMBOLSADO'] = pd.to_numeric(df['VALOR_REEMBOLSADO'])

In [46]:
df.dtypes

ANO                           int64
MES                           int64
SENADOR                      object
TIPO_DESPESA                 object
CNPJ_CPF                     object
FORNECEDOR                   object
DOCUMENTO                    object
DATA                         object
DETALHAMENTO                 object
VALOR_REEMBOLSADO           float64
DATE                 datetime64[ns]
DIA                           int64
dtype: object

In [50]:
df.loc[df['VALOR_REEMBOLSADO'] > 100, 'MAIOR_QUE_100'] = 1

In [48]:
df['MAIOR_QUE_100'] = 0

In [54]:
df.columns

Index(['ANO', 'MES', 'SENADOR', 'TIPO_DESPESA', 'CNPJ_CPF', 'FORNECEDOR',
       'DOCUMENTO', 'DATA', 'DETALHAMENTO', 'VALOR_REEMBOLSADO', 'DATE', 'DIA',
       'MAIOR_QUE_100'],
      dtype='object')

In [59]:
df = df.filter(['ANO', 'MES','DIA', 'SENADOR', 'TIPO_DESPESA','FORNECEDOR', 'DOCUMENTO', 'DETALHAMENTO', 'DATA', 'VALOR_REEMBOLSADO', 'DATE', 'MAIOR_QUE_100'])

In [60]:
df.head()

,ANO,MES,DIA,SENADOR,TIPO_DESPESA,FORNECEDOR,DOCUMENTO,DETALHAMENTO,DATA,VALOR_REEMBOLSADO,DATE,MAIOR_QUE_100
0,2016,1,13,ACIR GURGACZ,"Aluguel de imóveis para escritório político, c...",ELETROBRÁS DISTRIBUIÇÃO RONDÔNIA,000011328,Despesa com pagamento de energia elétrica para...,13-01-2016,73.60,2016-01-13,0
1,2016,1,18,ACIR GURGACZ,"Aluguel de imóveis para escritório político, c...",ELETROBRÁS DISTRIBUIÇÃO RONDÔNIA,000011327,Pagamento de energia elétrica para o escritóri...,18-01-2016,206.84,2016-01-18,1
2,2016,1,1,ACIR GURGACZ,"Aluguel de imóveis para escritório político, c...",GILBERTO PISELO DO NASCIMENTO,001/16,"Despesa com pagamento de aluguel, utilizado pa...",04-01-2016,6000.00,2016-04-01,1
3,2016,1,16,ACIR GURGACZ,"Aluguel de imóveis para escritório político, c...",OI MÓVEL S.A.,661639001,despesa com pagamento de telefonia para o escr...,16-01-2016,407.48,2016-01-16,1
4,2016,1,1,ACIR GURGACZ,Aquisição de material de consumo para uso no e...,AGÊNCIA ESTADO S.A.,00608918,Aquisição de publicação virtual de conteúdo jo...,06-01-2016,550.00,2016-06-01,1

In [63]:
df['TIPO_DESPESA'].unique()

array(['Aluguel de imóveis para escritório político, compreendendo despesas concernentes a eles.',
       'Aquisição de material de consumo para uso no escritório político, inclusive aquisição ou locação de software, despesas postais, aquisição de publicações, locação de móveis e de equipamentos. ',
       'Contratação de consultorias, assessorias, pesquisas, trabalhos técnicos e outros serviços de apoio ao exercício do mandato parlamentar',
       'Locomoção, hospedagem, alimentação, combustíveis e lubrificantes',
       'Passagens aéreas, aquáticas e terrestres nacionais',
       'Divulgação da atividade parlamentar',
       'Serviços de Segurança Privada'], dtype=object)

In [65]:
mapper = {'Aluguel de imóveis para escritório político, compreendendo despesas concernentes a eles.':'Aluguel de imóveis', 'Aquisição de material de consumo para uso no escritório político, inclusive aquisição ou locação de software, despesas postais, aquisição de publicações, locação de móveis e de equipamentos. ': 'Aquisição de material', 'Contratação de consultorias, assessorias, pesquisas, trabalhos técnicos e outros serviços de apoio ao exercício do mandato parlamentar': 'Contratações', 'Locomoção, hospedagem, alimentação, combustíveis e lubrificantes': 'Logística', 'Passagens aéreas, aquáticas e terrestres nacionais': 'Passagens', 'Divulgação da atividade parlamentar': 'Divulgação', 'Serviços de Segurança Privada': 'Segurança'}

df['TIPO_DESPESA'] = df['TIPO_DESPESA'].map(mapper)

In [67]:
df['TIPO_DESPESA'].unique()

array(['Aluguel de imóveis', 'Aquisição de material', 'Contratações',
       'Logística', 'Passagens', 'Divulgação', 'Segurança'], dtype=object)

In [70]:
df.head()

,ANO,MES,DIA,SENADOR,TIPO_DESPESA,FORNECEDOR,DOCUMENTO,DETALHAMENTO,DATA,VALOR_REEMBOLSADO,DATE,MAIOR_QUE_100
0,2016,1,13,ACIR GURGACZ,Aluguel de imóveis,ELETROBRÁS DISTRIBUIÇÃO RONDÔNIA,000011328,Despesa com pagamento de energia elétrica para...,13-01-2016,73.60,2016-01-13,0
1,2016,1,18,ACIR GURGACZ,Aluguel de imóveis,ELETROBRÁS DISTRIBUIÇÃO RONDÔNIA,000011327,Pagamento de energia elétrica para o escritóri...,18-01-2016,206.84,2016-01-18,1
2,2016,1,1,ACIR GURGACZ,Aluguel de imóveis,GILBERTO PISELO DO NASCIMENTO,001/16,"Despesa com pagamento de aluguel, utilizado pa...",04-01-2016,6000.00,2016-04-01,1
3,2016,1,16,ACIR GURGACZ,Aluguel de imóveis,OI MÓVEL S.A.,661639001,despesa com pagamento de telefonia para o escr...,16-01-2016,407.48,2016-01-16,1
4,2016,1,1,ACIR GURGACZ,Aquisição de material,AGÊNCIA ESTADO S.A.,00608918,Aquisição de publicação virtual de conteúdo jo...,06-01-2016,550.00,2016-06-01,1

In [71]:
df.to_csv('dados_limpos.csv', index=False)